name: 'Setup shellcheck'

description: |
  Install shellcheck into /usr/local/bin

inputs:
  version:
    description: 'Version of shellcheck to install'
    required: true
    default: 'stable'

runs:
  using: 'composite'
  steps:
    - name: "Install shellcheck"
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        TEMP_D=""
        XDIR=/usr/local/bin
        fail() { echo "FATAL:" "$@"; exit 1; }
        cleanup() {
          [ -d "$TEMP_D" ] || return 0
          rm -Rf "$TEMP_D"
        }

        TEMP_D=$(mktemp -d) || fail "could not create a temp dir"
        trap cleanup EXIT

        cd "$TEMP_D" || fail "could not cd to $TEMP_D"

        [ -n "$VERSION" ] || fail "version input is empty"
        case "$VERSION" in
            stable|latest|v[0-9]*) :;;
            *) fail "unexpected version $VERSION";;
        esac

        m=$(uname -m)
        case "$m" in
          x86_64|aarch64) arch=$m;;
          *) fail "unknown output for 'uname -m': '$m'";;
        esac
        uname_s=$(uname -s) || fail "uname -s failed"
        case "$uname_s" in
            Linux) platform=linux;;
            *) fail "unknown output from 'uname -s': $uname_s";;
        esac
        fname="shellcheck_${platform}.tar.gz"

        fname="shellcheck-$VERSION.$platform.$arch.tar.xz"
        burl="https://github.com/koalaman/shellcheck/releases/download"
        url="$burl/$VERSION"

        echo "download shellcheck for $platform/$arch from $url"
        curl -sL "$url/$fname" > "$fname" ||
          fail "download failed $url"

        echo "extract to $XDIR"
        mkdir -p "$XDIR"
        tar -C "$XDIR" --strip-components=1 -xvf "$fname" \
            "shellcheck-$VERSION/shellcheck"
    - name: "Show shellcheck info"
      shell: bash
      run: |
        set -x
        which shellcheck
        /usr/local/bin/shellcheck --version
