name: Presubmit

on:
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  test:
    name: Test Projects
    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: chainguard-dev/actions/setup-melange@8afa7cbd838d891038b3169777ad08bc3b544874

    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: './tw/go.mod'
        cache-dependency-path: '**/*.sum'

    - name: Build
      run: make build

    - name: Test all projects
      run: make test
