name: Presubmit

on:
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  test:
    name: Test Projects
    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: chainguard-dev/actions/setup-melange@260d16535ac5f2216abc306e80e6bb9f55ed86df

    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: './go.work'
        cache-dependency-path: '**/*.sum'

    - name: Build
      run: make build

    - name: Test all projects
      run: |
        ls -laht $HOME/go/pkg/mod
        
        # make build chowns is b/c its written to in docker which runs as root
        sudo chown -R $(id -u):$(id -g) $HOME/go/pkg/mod

        make test
