name: Presubmit

on:
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  test:
    name: Test Projects
    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: chainguard-dev/actions/apt-faster@ae2f0393ff2a60c572ff4d3485f406e8f36dfd38 # v1.4.6
    - uses: chainguard-dev/actions/setup-melange@ae2f0393ff2a60c572ff4d3485f406e8f36dfd38 # v1.4.6

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: './go.work'
        cache-dependency-path: '**/*.sum'

    - name: Build
      run: make build

    - name: Test all projects
      run: |
        make test
