name: Presubmit

on:
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  test:
    name: Test Projects
    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: chainguard-dev/actions/setup-melange@8afa7cbd838d891038b3169777ad08bc3b544874

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: './go.work'
        cache-dependency-path: '**/*.sum'

    - name: Build
      run: make build

    - name: Test all projects
      run: |
        ls -laht $HOME/go/pkg/mod
        
        # make build chowns is b/c its written to in docker which runs as root
        sudo chown -R $(id -u):$(id -g) $HOME/go/pkg/mod

        make test
